analyzer/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('students/',include(('students.urls','students'),namespace="students")),
    path('accounts/', include('django.contrib.auth.urls')),
]

students/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('',views.home, name='home'),
    path('profile',views.index, name='profile'),
    path('login', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('password_reset', auth_views.PasswordResetView.as_view(template_name='password_reset.html'), name='password_reset'),
    path('register', views.register, name='register'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
]

lecturers/models.py
from django.db import models

# Create your models here.

students/models.py
from django.db import models
from django.contrib.auth.models import ( User)

# Create your models here.
class MyUser(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    course_name = models.CharField(max_length=100,blank=True, null=True)

students/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')
    course_name = forms.CharField(max_length=100, required=True, help_text='Please enter your course name')

    class Meta:
        model = User
        fields = ('username', 'email', 'course_name' ,'password1', 'password2', )

lecturers/views.py
from django.shortcuts import render

# Create your views here.

students/views.py
from django.contrib.auth import login, authenticate, logout
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from .forms import SignUpForm

# Create your views here.

def home(request):
    return render(request, 'home.html',{})

def index(request):
    return render(request, 'profile.html',{})

def register(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('students:login')
    else:
        form = SignUpForm()
    return render(request, 'register.html', {'form': form})
def logout_view(request):
    logout(request)

students/templates/home.html
{% extends 'base.html'%}

students/templates/login.html
{% extends 'base.html' %}
{% load bootstrap  %}
{% block topcontent %}
<div class="container" style="margin-top:10px;width: 450px;">
{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
{% endif %}
  <div class="card">
        <div class="card-header">Student Login</div>
          <div class="card-body">

            <form method="post" action="{% url 'students:login' %}">
            {% csrf_token %}
            {{ form|bootstrap }}

            <input type="submit" value="login">
            <input type="hidden" name="next" value="{{ next }}">
            </form>
            {# Assumes you setup the password_reset view in your URLconf #}
            <p><a href="{% url 'students:password_reset' %}">Reset password?</a></p>
            <p><a href="{% url 'students:register' %}">Register?</a></p>
          </div>
        </div>
</div>


{% endblock %}

students/templates/password_reset.html
{% extends 'base.html' %}
{% load bootstrap %}
{% block  topcontent %}

  <div class="container" style="margin-top:10px;width: 450px;">
    <div class="card">
      <div class="card-header">
        Forgot Password
      </div>
      <div class="card-body">
        <form method="post">
          {% csrf_token %}
          {{ form|bootstrap }}
          <button type="submit">Submit</button>
        </form>
      </div>
  </div>
  </div>
{% endblock %}

students/templates/profile.html
{% extends 'base.html' %}
{% block topcontent %}

                <div class="container">
                  <div class="row profile">
                        <div class="col-md-3">
                        <div class="profile-sidebar">
                          <!-- SIDEBAR USERPIC -->
                          <div class="profile-userpic">
                            <img src="https://static.change.org/profile-img/default-user-profile.svg" class="img-responsive" alt="">
                          </div>
                          <!-- END SIDEBAR USERPIC -->
                          <!-- SIDEBAR USER TITLE -->
                          <div class="profile-usertitle">
                            <div class="profile-usertitle-name">
                              {{user.username}}
                            </div>
                            <div class="profile-usertitle-job">
                              {{user.email}}
                            </div>
                          </div>
                          <!-- END SIDEBAR USER TITLE -->
                          <!-- SIDEBAR BUTTONS -->
                          <div class="profile-userbuttons">
                            <!-- <button type="button" class="btn btn-success btn-sm">Follow</button> -->
                            <button type="button" class="btn btn-danger btn-sm">Message</button>
                          </div>
                          <!-- END SIDEBAR BUTTONS -->
                          <!-- SIDEBAR MENU -->
                          <div class="profile-usermenu">
                            <ul class="nav">
                              <li class="active">
                                <a href="#">
                                <i class="glyphicon glyphicon-home"></i>
                                Overview </a>
                              </li>
                              <li>
                                <a href="#">
                                <i class="glyphicon glyphicon-user"></i>
                                Account Settings </a>
                              </li>
                              <li>
                                <a href="#" target="_blank">
                                <i class="glyphicon glyphicon-ok"></i>
                              Ask a question</a>
                              </li>
                              <li>
                                <a href="#">
                                <i class="glyphicon glyphicon-flag"></i>
                                Review a course </a>
                              </li>
                            </ul>
                          </div>
                          <!-- END MENU -->

                        </div>
                        </div>
                        <div class="col-md-9">
                              <div class="profile-content">
                                  <div class="card-header">
                                      Courses Taken:
                                  </div>
                                  <ul>
                                    <li>{{myuser.course_name}}</li>
                                  </ul>
                              </div>
                        </div>
                        </div>
                </div>

          </body>

{% endblock %}

students/templates/register.html
{% extends 'base.html' %}
{% load bootstrap  %}
{% block topcontent %}
        <div class="container align-items-center d-flex " style="margin-top:10px;width: 1000px;">
          <div class="card" style="width:800px;">
                <div class="card-header">Student Sign Up</div>
                  <div class="card-body" style="width:750px;">
              <form method="post">
                {% csrf_token %}
                {{ form|bootstrap }}
                <button type="submit">Sign up</button>
              </form>
            </div>
          </div>
        </div>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
      <meta charset="utf-8">
      <title>Home</title>
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
      <link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
      <link rel="stylesheet" href="{% static 'css/style.css' %}" >
      <link href="{% static 'css/carousel.css' %}" rel="stylesheet">
      <link href="{% static 'css/custom.css' %}" rel="stylesheet">
      <link href="{% static 'css/scrolling-nav.css' %}" rel="stylesheet" >
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>
  <body>
          <nav class="navbar navbar-expand-lg navbar-light bg-light p-1 fixed-top" id="mainNav">
            <a class="navbar-brand" href="#">
            <img src="{% static 'images/letter1.png' %}" height = 40 width=40 style="padding-right:10px;" class="d-inline-block align-top" alt="">Analyzer</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
              <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                  <a class="nav-link js-scroll-trigger" href="{% url 'students:home' %}">Home</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link js-scroll-trigger" href="#services">Services</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link js-scroll-trigger" href="#contact">Contact</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#">Questions</a>
                </li>
              </ul>
            </div>

              <div class="collapse navbar-collapse">
                  <div class="navbar-nav ml-auto">
                    {% if user.is_authenticated %}
                    <a class="nav-item nav-link" href="{% url 'students:logout' %}">Logout</a>
                    {% else %}
                    <a class="nav-item nav-link" href="{% url 'students:login' %}">Login</a>
                    <a class="nav-item nav-link" href="{% url 'students:register' %}">Signup</a>
                    {% endif %}
                  </div>
                </div>
            </div>
          </nav>

          <!-- breadcrumbs -->
          {% block topcontent %}
            {% block content %}
            <nav aria-label="breadcrumb">
                  <ol class="breadcrumb">
                  <li class="breadcrumb-item active" aria-current="page">Home</li>
                  </ol>
            </nav>
          <!-- end of breadcrumbs -->

          <header class="bg-dark text-light">
            <div class="container text-center">
              <h1>Welcome to Analyzer</h1>
              <p class="lead">Where ideas begin...</p>
            </div>
          </header>

          <section id="about">
            <div class="container">
              <div class="row">
                <div class="col-lg-8 mx-auto">
                  <h2>About Us</h2>
                  <p class="lead">This is a great place to ask any programming question.</p>
                </div>
              </div>
            </div>
          </section>

          <section id="services" class="bg-light">
            <div class="container">
              <div class="row">
                <div class="col-lg-8 mx-auto">
                  <h2>Services we offer</h2>
                  <p class="lead">We provide detailed analysis to lecturers about performance of students</p>
                </div>
              </div>
            </div>
          </section>

          <section id="contact">
            <div class="container">
              <div class="row">
                <div class="col-lg-8 mx-auto">
                  <h2>Contact us</h2>
                  <p class="lead">Feel free to reach out to us inorder to help us improve your interaction with the system.</p>
                </div>
              </div>
            </div>
          </section>
          {% endblock%}
          <!-- Footer -->
      <footer class="py-5 bg-dark">
        <div class="container">
          <p class="m-0 text-center text-white">Copyright &copy; @dennoh Website 2018</p>
        </div>
        <!-- /.container -->
      </footer>
        {% endblock topcontent %}


            <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
            <script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
            <!-- Bootstrap core JavaScript -->
             <script src="{% static 'js/jquery.min.js' %}"></script>
             <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

             <!-- Plugin JavaScript -->
             <script src="{% static 'js/jquery.easing.min.js' %}"></script>

             <!-- Custom JavaScript for this theme -->
             <script src="{% static 'js/scrolling-nav.js' %}"></script>


      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>